#!/usr/bin/env python3
"""
Map saving utility for saving occupancy maps to PGM/PNG format.
Compatible with ROS 2 nav_msgs/OccupancyGrid format.
"""
import sys
import os
# Add user site-packages to path to find numpy
user_site_packages = os.path.expanduser('~/.local/lib/python3.10/site-packages')
if os.path.exists(user_site_packages) and user_site_packages not in sys.path:
    sys.path.insert(0, user_site_packages)

import numpy as np
from pathlib import Path
from datetime import datetime
import math


class MapSaver:
    """Utility class for saving occupancy maps to various formats."""
    
    def __init__(self, map_resolution=0.05, occupied_threshold=0.65, free_threshold=0.25):
        """
        Initialize the map saver.
        
        Args:
            map_resolution: Resolution of the map in meters per cell
            occupied_threshold: Probability threshold for occupied cells
            free_threshold: Probability threshold for free cells
        """
        self.map_resolution = map_resolution
        self.occupied_threshold = occupied_threshold
        self.free_threshold = free_threshold
    
    def save_map_to_pgm(self, free_counts, occupied_counts, map_origin_x, map_origin_y, 
                        map_resolution, filename=None, metadata=None):
        """
        Save the occupancy map to PGM format.
        
        Args:
            free_counts: Dictionary of (x, y) -> count of free observations
            occupied_counts: Dictionary of (x, y) -> count of occupied observations
            map_origin_x: X coordinate of map origin (world coordinates)
            map_origin_y: Y coordinate of map origin (world coordinates)
            map_resolution: Resolution of the map in meters per cell
            filename: Output filename (if None, generates one with timestamp)
            metadata: Optional dictionary of metadata to include in YAML header
        
        Returns:
            Path to the saved file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"map_{timestamp}.pgm"
        
        # Determine map boundaries
        all_cells = set(free_counts.keys()) | set(occupied_counts.keys())
        
        if not all_cells:
            raise ValueError("No map data to save")
        
        min_x = min(cell[0] for cell in all_cells)
        max_x = max(cell[0] for cell in all_cells)
        min_y = min(cell[1] for cell in all_cells)
        max_y = max(cell[1] for cell in all_cells)
        
        width = max_x - min_x + 1
        height = max_y - min_y + 1
        
        # Create numpy array for the map (0=free, 100=occupied, -1=unknown)
        map_data = np.full((height, width), -1, dtype=np.int8)
        
        # Fill in known cells
        for cell, count in free_counts.items():
            cell_x, cell_y = cell
            array_x = cell_x - min_x
            array_y = height - 1 - (cell_y - min_y)  # Flip Y axis for image coordinates
            if count > 0:
                map_data[array_y, array_x] = 0  # Free
        
        for cell, count in occupied_counts.items():
            cell_x, cell_y = cell
            array_x = cell_x - min_x
            array_y = height - 1 - (cell_y - min_y)
            if count > 0:
                map_data[array_y, array_x] = 100  # Occupied
        
        # Save as PGM
        with open(filename, 'w') as f:
            # Write YAML header (ROS compatible)
            f.write("# ROS2 OccupancyGrid Map\n")
            f.write("# Generated by BumperBot Room Vacuum Controller\n")
            if metadata:
                f.write(f"# Metadata: {metadata}\n")
            f.write(f"# Resolution: {map_resolution}\n")
            f.write(f"# Origin: [{map_origin_x}, {map_origin_y}, 0.0]\n")
            f.write(f"# Map size: {width}x{height}\n")
            f.write(f"# Occupied threshold: {self.occupied_threshold}\n")
            f.write(f"# Free threshold: {self.free_threshold}\n")
            
            # Write PGM header
            f.write("P2\n")
            f.write(f"{width} {height}\n")
            f.write("100\n")
            
            # Write pixel data
            for row in map_data:
                line = " ".join(str(int(pixel)) if pixel >= 0 else "-1" for pixel in row)
                f.write(line + "\n")
        
        return Path(filename)
    
    def save_map_to_numpy(self, free_counts, occupied_counts, min_x, max_x, min_y, max_y):
        """
        Convert map data to numpy array.
        
        Args:
            free_counts: Dictionary of (x, y) -> count
            occupied_counts: Dictionary of (x, y) -> count
            min_x, max_x, min_y, max_y: Map boundaries
        
        Returns:
            numpy array with values: -1 (unknown), 0 (free), 100 (occupied)
        """
        width = max_x - min_x + 1
        height = max_y - min_y + 1
        map_array = np.full((height, width), -1, dtype=np.int8)
        
        for cell, count in free_counts.items():
            cell_x, cell_y = cell
            if min_x <= cell_x <= max_x and min_y <= cell_y <= max_y:
                array_x = cell_x - min_x
                array_y = height - 1 - (cell_y - min_y)
                if count > 0:
                    map_array[array_y, array_x] = 0
        
        for cell, count in occupied_counts.items():
            cell_x, cell_y = cell
            if min_x <= cell_x <= max_x and min_y <= cell_y <= max_y:
                array_x = cell_x - min_x
                array_y = height - 1 - (cell_y - min_y)
                if count > 0:
                    map_array[array_y, array_x] = 100
        
        return map_array


def save_occupancy_map(free_counts, occupied_counts, origin_x, origin_y, resolution, 
                       output_dir=".", map_name=None):
    """
    Convenience function to save an occupancy map.
    
    Args:
        free_counts: Dictionary of (cell_x, cell_y) -> free observation count
        occupied_counts: Dictionary of (cell_x, cell_y) -> occupied observation count
        origin_x: World X coordinate of map origin
        origin_y: World Y coordinate of map origin
        resolution: Map resolution in meters per cell
        output_dir: Directory to save the map
        map_name: Base name for the map file
    
    Returns:
        Path to the saved map file
    """
    saver = MapSaver(resolution)
    
    # Get map boundaries
    all_cells = list(free_counts.keys()) + list(occupied_counts.keys())
    if not all_cells:
        raise ValueError("No map data available")
    
    min_x = min(cell[0] for cell in all_cells)
    max_x = max(cell[0] for cell in all_cells)
    min_y = min(cell[1] for cell in all_cells)
    max_y = max(cell[1] for cell in all_cells)
    
    # Create output directory if it doesn't exist
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate filename
    if map_name is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        map_name = f"room_map_{timestamp}"
    
    pgm_filename = output_dir / f"{map_name}.pgm"
    yaml_filename = output_dir / f"{map_name}.yaml"
    
    # Save PGM
    metadata = {
        "image": f"{map_name}.pgm",
        "resolution": resolution,
        "origin": [origin_x, origin_y, 0.0],
        "negate": 0,
        "occupied_thresh": 0.65,
        "free_thresh": 0.25,
    }
    saver.save_map_to_pgm(free_counts, occupied_counts, origin_x, origin_y, 
                          resolution, str(pgm_filename), metadata)
    
    # Save YAML metadata
    with open(yaml_filename, 'w') as f:
        f.write(f"image: {map_name}.pgm\n")
        f.write(f"resolution: {resolution}\n")
        f.write(f"origin: [{origin_x}, {origin_y}, 0.0]\n")
        f.write(f"negate: 0\n")
        f.write(f"occupied_thresh: 0.65\n")
        f.write(f"free_thresh: 0.25\n")
    
    return pgm_filename


if __name__ == '__main__':
    print("Map Saver utility - use via import")
