#!/usr/bin/env python3
"""
R6.7 - Deterministic SDF ``<heightmap>`` terrain arena generator.

The existing terrain arenas (``terrain_rough``, ``terrain_stairs``,
``terrain_stepping_stones``) are built from axis-aligned boxes. They cannot
represent a slope, a ridge or any continuous elevation, and no registered map
in this package used ``<heightmap>`` at all, so the shared heightfield
converter had nothing real to run against.

This emits ``terrain_heightfield``: a seeded 20 m x 20 m heightmap covering a
smooth ridge, a valley and a genuine step, as

* a grayscale PNG raster (the SDF ``<heightmap>`` ``<uri>``),
* a ``.world`` whose single collision *is* that heightmap,
* an occupancy PGM/YAML rasterised from the same elevation field, so the 2D
  map and the 3D surface describe one object.

Determinism: the surface is a closed-form sum of sines of the map seed, so
regenerating reproduces byte-identical PNG, world and occupancy files.

The elevation convention deliberately matches what was measured against the
installed Gazebo (see ``robot_lab_utils/heightfield.py``): intensity is
normalised by the raster maximum, row 0 is maximum +y, and the grid is
cell-centred across ``(n-1)/2 * size/n``.

usage:
    python3 tools/gen_heightfield_arena.py [--out-dir DIR] [--check]
"""

from __future__ import annotations

import argparse
import hashlib
import io
from pathlib import Path

import numpy as np
from PIL import Image

WORLD_NAME = "terrain_heightfield"
SIZE_X = 20.0        # metres, SDF <size> x
SIZE_Y = 20.0        # metres, SDF <size> y
SIZE_Z = 3.0         # metres, SDF <size> z (elevation range)
SAMPLES = 129        # 2^7 + 1, the power-of-two-plus-one heightmap convention
RESOLUTION = 0.05    # occupancy metres per cell
FREE = 254
OCCUPIED = 0
# Occupancy is the slice a flat-based robot sees; anything taller than the
# step is an obstacle for it.
SLICE_HEIGHT = 0.25


def elevation(x: np.ndarray, y: np.ndarray, seed: int) -> np.ndarray:
    """Closed-form terrain elevation in metres over the arena footprint.

    A ridge across x, a valley along y and a flat plateau give slopes, a
    depression and a real step edge - the shapes a box arena cannot express.
    """
    phase = seed * 0.37
    ridge = 1.6 * np.sin(x / 6.0 + phase)
    valley = 1.2 * np.cos(y / 5.0 - phase)
    undulation = 0.35 * np.sin(x / 2.5) * np.cos(y / 2.5 + phase)
    # A step on the +x side: a genuine discontinuity in the surface.
    step = np.where(x > 4.0, 1.1, 0.0)
    return ridge + valley + undulation + step


def build_raster(seed: int):
    """Return (PIL image, elevation metres, peak metres) for the arena.

    The raster covers the SDF ``<size>`` footprint on the cell-centred grid the
    measured convention expects.
    """
    cell_x = SIZE_X / SAMPLES
    cell_y = SIZE_Y / SAMPLES
    xs = (np.arange(SAMPLES) + 0.5) * cell_x - SIZE_X / 2.0
    ys = SIZE_Y / 2.0 - (np.arange(SAMPLES) + 0.5) * cell_y  # row 0 = +y
    grid_x, grid_y = np.meshgrid(xs, ys)
    heights = elevation(grid_x, grid_y, seed)
    heights = heights - heights.min()   # elevation is measured from the pose
    peak = float(heights.max())
    if peak <= 0:
        raise ValueError("degenerate terrain")
    # Intensity is normalised by the raster maximum; make that explicit rather
    # than assuming a full-scale 255.
    intensity = np.rint(heights / peak * 255.0).astype(np.uint8)
    return Image.fromarray(intensity, "L"), heights, peak


def build_world(raster_name: str) -> str:
    geometry = (f"<heightmap><uri>{raster_name}</uri>"
                f"<size>{SIZE_X:g} {SIZE_Y:g} {SIZE_Z:g}</size></heightmap>")
    return f"""<?xml version="1.0"?>
<!-- Generated by tools/gen_heightfield_arena.py - do not edit by hand. -->
<sdf version="1.7">
  <world name="{WORLD_NAME}">
    <physics type="ode">
      <max_step_size>0.01</max_step_size>
    </physics>
    <light name="sun" type="directional">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 20 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <direction>-0.5 0.3 -1.0</direction>
    </light>
    <model name="terrain">
      <static>true</static>
      <!-- Elevation is measured from this pose, not centred on it. -->
      <pose>0 0 0 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry>{geometry}</geometry>
          <surface>
            <friction><ode><mu>100</mu><mu2>50</mu2></ode></friction>
          </surface>
        </collision>
        <visual name="visual">
          <geometry>{geometry}</geometry>
        </visual>
      </link>
    </model>
    <model name="spawn_marker">
      <static>true</static>
      <pose>-6 -6 0.02 0 0 0</pose>
      <link name="link">
        <visual name="visual">
          <geometry><box><size>0.4 0.4 0.02</size></box></geometry>
          <material>
            <ambient>0.1 0.8 0.1 1</ambient>
            <diffuse>0.1 0.8 0.1 1</diffuse>
          </material>
        </visual>
      </link>
    </model>
  </world>
</sdf>
"""


def build_occupancy(heights: np.ndarray, peak: float):
    """Rasterise the same elevation field at SLICE_HEIGHT.

    Derived from ``heights`` rather than from the PNG, so the occupancy map
    and the 3D terrain are two projections of one field and cannot drift.
    """
    margin = 1.0
    lo_x, hi_x = -SIZE_X / 2.0 - margin, SIZE_X / 2.0 + margin
    lo_y, hi_y = -SIZE_Y / 2.0 - margin, SIZE_Y / 2.0 + margin
    columns = int(round((hi_x - lo_x) / RESOLUTION))
    rows = int(round((hi_y - lo_y) / RESOLUTION))
    grid = np.full((rows, columns), FREE, dtype=np.uint8)

    metres = heights * (SIZE_Z / peak)      # same normalisation the 3D uses
    cell_x = SIZE_X / SAMPLES
    cell_y = SIZE_Y / SAMPLES
    solid = metres >= SLICE_HEIGHT
    # Vectorised scatter: the occupancy grid is axis-aligned, so each terrain
    # sample maps to one cell without a python loop over SAMPLES**2.
    xs = (np.arange(SAMPLES) + 0.5) * cell_x - SIZE_X / 2.0
    ys = SIZE_Y / 2.0 - (np.arange(SAMPLES) + 0.5) * cell_y
    pixel_columns = np.rint((xs - lo_x) / RESOLUTION).astype(int)
    pixel_rows = np.rint((hi_y - ys) / RESOLUTION).astype(int)
    keep = ((pixel_columns >= 0) & (pixel_columns < columns) &
            (pixel_rows >= 0) & (pixel_rows < rows))
    grid[np.ix_(pixel_rows[keep], pixel_columns[keep])] = np.where(
        solid[:, keep], OCCUPIED, grid[np.ix_(pixel_rows[keep],
                                              pixel_columns[keep])])

    pgm = b"P5\n%d %d\n255\n" % (columns, rows) + grid.tobytes()
    map_yaml = (
        f"image: map.pgm\n"
        f"mode: trinary\n"
        f"resolution: {RESOLUTION:.3f}\n"
        f"origin: [{lo_x:.3f}, {lo_y:.3f}, 0.000000]\n"
        f"negate: 0\n"
        f"occupied_thresh: 0.65\n"
        f"free_thresh: 0.196\n"
    )
    return pgm, map_yaml, int(np.sum(grid == OCCUPIED)), (columns, rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        default=str(Path(__file__).resolve().parent.parent / "maps"))
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--check", action="store_true",
                        help="fail when the checked-in arena differs")
    args = parser.parse_args()

    out_dir = Path(args.out_dir) / WORLD_NAME
    raster_name = "terrain.png"
    image, heights, peak = build_raster(args.seed)
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")

    world_path = out_dir / "worlds" / f"{WORLD_NAME}.world"
    yaml_path = out_dir / "maps" / "map.yaml"
    pgm_path = out_dir / "maps" / "map.pgm"
    # The raster sits beside the world file: SDF resolves a relative <uri>
    # against the world's own directory, and Gazebo does the same. Keeping it
    # in worlds/ is what makes the URI resolve for every backend reader.
    raster_path = out_dir / "worlds" / raster_name
    pgm, map_yaml, occupied, shape = build_occupancy(heights, peak)
    artifacts = {world_path: build_world(raster_name).encode("utf-8"),
                 yaml_path: map_yaml.encode("utf-8"),
                 pgm_path: pgm,
                 raster_path: buffer.getvalue()}

    if args.check:
        stale = [str(path) for path, data in artifacts.items()
                 if not path.is_file() or path.read_bytes() != data]
        if stale:
            print("Out-of-date heightfield arena: %s"
                  % ", ".join(os.path.basename(p) for p in stale))
            return 1
        print("Heightfield arena is up to date.")
        return 0

    for path, data in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    raster_max = int(np.asarray(image).max())
    print(f"{WORLD_NAME}: raster {SAMPLES}x{SAMPLES}, peak {peak:.3f} m, "
          f"raster max {raster_max}, occupancy {occupied}/"
          f"{shape[0] * shape[1]} cells at {SLICE_HEIGHT} m slice, "
          f"seed {args.seed}")
    print(f"  sha256(world)  = {hashlib.sha256(artifacts[world_path]).hexdigest()[:16]}")
    print(f"  sha256(raster) = {hashlib.sha256(artifacts[raster_path]).hexdigest()[:16]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
